apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-grafana-datasources
  namespace: monitoring
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://192.168.0.140/
      access: proxy
      isDefault: true